name = "saveyourweb-contact"
main = "src/index.ts"
compatibility_date = "2026-03-10"

[vars]
NOTIFY_EMAIL = "contact@saveyourweb.fr"
ALLOWED_ORIGIN = "https://saveyourweb.fr"
DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1480926931045060762/muTuIjvhPvPX4YxedoUAzr6TmwpUvVFiMhIpIdLlhn5M1s5MIbqqEYGIKIQV4lpUi-Im"
DISCORD_DEVIS_WEBHOOK_URL = "https://discord.com/api/webhooks/1480958629589942372/8RnbG_hIHpNFPwIikO8iMXXWJSvnRsBeY4-HWtbVjB9nIXa-QJ-PcVzarzVHDFA5ZNog"
